/**:
  ros__parameters:
    network:
      config: "./darknet/yolov3-tiny.cfg"
      weights: "./darknet/yolov3-tiny.weights"
      class_names: "./darknet/coco.names"
    detection:
      enable: true
      threshold: 0.25
      nms_threshold: 0.45
